'use client';

import Link from 'next/link';
import { Box, LayoutDashboard, Package, Tags, ShoppingCart, Settings, LogOut } from 'lucide-react';
import { useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase';

export default function AdminPage() {
  const [stats,setStats]=useState([['Pedidos hoje','0'],['Produtos ativos','0'],['Vendas no mês','R$ 0,00'],['Pedidos pendentes','0']]);
  useEffect(()=>{async function load(){if(!supabase)return;const [{count:products},{data:orders}]=await Promise.all([supabase.from('products').select('*',{count:'exact',head:true}).eq('active',true),supabase.from('orders').select('status,total,created_at')]);const now=new Date();const today=now.toDateString();const month=now.getMonth();const year=now.getFullYear();const list=orders??[];const todayCount=list.filter(o=>new Date(o.created_at).toDateString()===today).length;const monthSales=list.filter(o=>{const d=new Date(o.created_at);return d.getMonth()===month&&d.getFullYear()===year&&o.status!=='cancelled'}).reduce((s,o)=>s+Number(o.total),0);const pending=list.filter(o=>['pending','confirmed','preparing'].includes(o.status)).length;setStats([['Pedidos hoje',String(todayCount)],['Produtos ativos',String(products??0)],['Vendas no mês',`R$ ${monthSales.toFixed(2).replace('.',',')}`],['Pedidos pendentes',String(pending)]]);}load()},[]);
 async function logout(){await supabase?.auth.signOut();window.location.href='/admin/login'}
 return <main><div className="topbar">Painel administrativo • 2P Box</div><header className="header container"><Link href="/" className="brand"><div className="brand-mark">2P</div><div><strong>2P BOX</strong><small>PAINEL ADMINISTRATIVO</small></div></Link><div style={{display:'flex',gap:8}}><Link href="/" className="secondary">Ver loja</Link><button className="secondary" onClick={logout} style={{border:0,cursor:'pointer'}}><LogOut size={16}/> Sair</button></div></header><section className="container section"><p className="eyebrow">GESTÃO DA LOJA</p><h1 style={{fontFamily:'Barlow Condensed',fontSize:52,textTransform:'uppercase',fontStyle:'italic',marginTop:0}}>Dashboard</h1><div className="category-grid">{stats.map(([label,value])=><div className="category" key={label}><small>{label}</small><h3 style={{fontSize:34}}>{value}</h3></div>)}</div><div className="category-grid" style={{marginTop:18}}><Link className="category" href="/admin/produtos"><Package size={25}/><h3>Produtos</h3><p>Adicionar, editar, excluir e controlar estoque.</p></Link><Link className="category" href="/admin/categorias"><Tags size={25}/><h3>Categorias</h3><p>Organizar o catálogo da 2P Box.</p></Link><Link className="category" href="/admin/pedidos"><ShoppingCart size={25}/><h3>Pedidos</h3><p>Acompanhar pedidos e status de retirada.</p></Link><div className="category"><Settings size={25}/><h3>Configurações</h3><p>WhatsApp e integrações de pagamento serão configurados na próxima etapa.</p></div></div></section><div className="benefits"><div className="container benefits-grid"><div><Box/><h3>Catálogo</h3><p>Produtos e estoque conectados ao Supabase.</p></div><div><LayoutDashboard/><h3>Pagamento</h3><p>Estrutura preparada para integração com Pagar.me.</p></div><div><ShoppingCart/><h3>Entrega</h3><p>Retirada na loja ou atendimento via WhatsApp para frete.</p></div></div></div></main>;
}
