'use client';

import { useMemo } from 'react';
import Link from 'next/link';
import { Minus, Plus, Trash2, ShoppingBag } from 'lucide-react';
import { useCart } from '@/components/cart-provider';

export default function CarrinhoPage(){
 const {items,setQty,remove,total}=useCart();
 return <main><div className="topbar">Qualidade <span>•</span> Variedade <span>•</span> Confiança</div><header className="header container"><Link href="/" className="brand"><div className="brand-mark">2P</div><div><strong>2P BOX</strong><small>TUDO QUE VOCÊ PRECISA, EM UM SÓ LUGAR.</small></div></Link><Link className="secondary" href="/loja">Continuar comprando</Link></header><section className="container section"><p className="eyebrow">SEU PEDIDO</p><h1 style={{fontFamily:'Barlow Condensed',fontSize:52,textTransform:'uppercase',fontStyle:'italic',marginTop:0}}>Carrinho</h1>{items.length===0?<div className="category" style={{maxWidth:760}}><ShoppingBag size={28}/><h3>Seu carrinho está vazio</h3><p>Adicione produtos para começar seu pedido.</p><Link className="primary" href="/loja">Explorar produtos</Link></div>:<><div style={{display:'grid',gap:12,maxWidth:820}}>{items.map(i=><div className="category" key={i.id} style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,flexWrap:'wrap'}}><div><h3>{i.name}</h3><strong>R$ {i.price.toFixed(2).replace('.',',')}</strong><p style={{margin:'5px 0 0'}}>Estoque disponível: {i.stock}</p></div><div style={{display:'flex',alignItems:'center',gap:8}}><button className="secondary" onClick={()=>setQty(i.id,i.quantity-1)} aria-label="Diminuir"><Minus size={15}/></button><strong>{i.quantity}</strong><button className="secondary" onClick={()=>setQty(i.id,i.quantity+1)} aria-label="Aumentar"><Plus size={15}/></button><button className="secondary" onClick={()=>remove(i.id)} aria-label="Remover"><Trash2 size={15}/></button></div></div>)}</div><div className="category" style={{maxWidth:820,marginTop:18,display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,flexWrap:'wrap'}}><div><small>TOTAL</small><h2 style={{margin:0}}>R$ {total.toFixed(2).replace('.',',')}</h2></div><Link className="primary" href="/checkout">Finalizar pedido</Link></div></>}</section></main>;
}
