'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, RefreshCw } from 'lucide-react';
import { supabase } from '@/lib/supabase';

type Order={id:string;customer_name:string;customer_phone:string;delivery_type:string;status:string;payment_status:string;total:number;created_at:string};
const labels:Record<string,string>={pending:'Pendente',confirmed:'Confirmado',preparing:'Preparando',ready:'Pronto',completed:'Concluído',cancelled:'Cancelado'};
export default function OrdersPage(){const [orders,setOrders]=useState<Order[]>([]);const [loading,setLoading]=useState(true);const [message,setMessage]=useState('');
 async function load(){if(!supabase)return;setLoading(true);const {data,error}=await supabase.from('orders').select('*').order('created_at',{ascending:false});if(error)setMessage(error.message);setOrders((data??[]) as Order[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 async function change(id:string,status:string){if(!supabase)return;const {error}=await supabase.from('orders').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error)setMessage(error.message);else load()}
 return <main><div className="topbar">Painel administrativo • 2P Box</div><header className="header container"><Link href="/admin" className="brand"><div className="brand-mark">2P</div><div><strong>2P BOX</strong><small>PEDIDOS</small></div></Link><button className="secondary" onClick={load} style={{border:0,cursor:'pointer'}}><RefreshCw size={16}/> Atualizar</button></header><section className="container section"><Link href="/admin" className="secondary"><ArrowLeft size={16}/> Painel</Link><p className="eyebrow" style={{marginTop:30}}>VENDAS</p><h1 style={{fontFamily:'Barlow Condensed',fontSize:56,textTransform:'uppercase',fontStyle:'italic',marginTop:0}}>Pedidos</h1>{message&&<p>{message}</p>}{loading?<p>Carregando pedidos...</p>:orders.length===0?<div className="category"><h3>Nenhum pedido ainda</h3><p>Os novos pedidos aparecerão aqui.</p></div>:<div style={{display:'grid',gap:14}}>{orders.map(o=><div className="category" key={o.id}><div style={{display:'flex',justifyContent:'space-between',gap:16,flexWrap:'wrap'}}><div><small>{new Date(o.created_at).toLocaleString('pt-BR')}</small><h3>{o.customer_name}</h3><p>{o.customer_phone} • {o.delivery_type==='pickup'?'Retirada na loja':'Frete via WhatsApp'}</p><strong>R$ {Number(o.total).toFixed(2).replace('.',',')}</strong></div><div style={{display:'grid',gap:8,minWidth:180}}><strong>{labels[o.status]||o.status}</strong><select value={o.status} onChange={e=>change(o.id,e.target.value)} style={{padding:10,border:'1px solid #ddd',borderRadius:8}}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div></div></div>)}</div>}</section></main>}
