'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Plus, Save, Trash2 } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { SiteHeader } from '@/components/site-header';
import { useToast } from '@/components/ui/toast';
export default function AdminImpressao(){const toast=useToast();const[papers,setPapers]=useState<any[]>([]);const[tiers,setTiers]=useState<any[]>([]);const[services,setServices]=useState<any[]>([]);const[loading,setLoading]=useState(true);const load=async()=>{if(!supabase)return;const[a,b,c]=await Promise.all([supabase.from('print_paper_types').select('*').order('sort_order'),supabase.from('print_price_tiers').select('*').order('min_sheets'),supabase.from('print_services').select('*').order('sort_order')]);setPapers(a.data||[]);setTiers(b.data||[]);setServices(c.data||[]);setLoading(false)};useEffect(()=>{void load()},[]);
async function save(table:string,row:any){if(!supabase)return;const payload={...row};for(const k of ['min_sheets','max_sheets','sort_order'])if(payload[k]==='')payload[k]=null;for(const k of ['min_sheets','max_sheets','sort_order'])if(payload[k]!=null)payload[k]=Number(payload[k]);if(payload.price_per_sheet!=null)payload.price_per_sheet=Number(payload.price_per_sheet);if(payload.price!=null)payload.price=Number(payload.price);const{error}=await supabase.from(table).upsert(payload);if(error)toast.error('Não foi possível salvar',error.message);else{toast.success('Salvo');void load()}}async function del(table:string,id:string){if(!supabase)return;const{error}=await supabase.from(table).delete().eq('id',id);if(error)toast.error('Não foi possível excluir',error.message);else void load()}
if(loading)return <main><SiteHeader variant="admin" subtitle="IMPRESSÃO"/><div className="loading">Carregando...</div></main>;
return <main className="pa"><SiteHeader variant="admin" subtitle="IMPRESSÃO"/><section className="shell"><Link href="/admin" className="back"><ArrowLeft size={15}/> Painel</Link><header><p>IMPRESSÃO</p><h1>Central de impressão</h1><span>Configure papel, preço por quantidade de folhas e serviços.</span></header>
<section className="card"><div className="title"><div><b>Tipos de papel</b><small>Padrão A4, Foto, Canson e outros.</small></div><button onClick={()=>setPapers(v=>[...v,{id:crypto.randomUUID(),name:'Novo papel',size:'A4',active:true,sort_order:v.length}])}><Plus size={14}/> Novo</button></div>{papers.map(p=><div className="paper" key={p.id}><input value={p.name} onChange={e=>setPapers(v=>v.map(x=>x.id===p.id?{...x,name:e.target.value}:x))}/><input value={p.size} onChange={e=>setPapers(v=>v.map(x=>x.id===p.id?{...x,size:e.target.value}:x))}/><label><input type="checkbox" checked={p.active} onChange={e=>setPapers(v=>v.map(x=>x.id===p.id?{...x,active:e.target.checked}:x))}/> Ativo</label><button onClick={()=>void save('print_paper_types',p)}><Save size={14}/></button><button onClick={()=>void del('print_paper_types',p.id)}><Trash2 size={14}/></button></div>)}</section>
<section className="card"><div className="title"><div><b>Faixas de preço</b><small>Preço por folha conforme a quantidade total de folhas.</small></div><button onClick={()=>setTiers(v=>[...v,{id:crypto.randomUUID(),paper_type_id:papers[0]?.id||'',color_mode:'bw',min_sheets:1,max_sheets:'',price_per_sheet:0}])}><Plus size={14}/> Nova faixa</button></div><div className="rows">{tiers.map(t=><div className="row" key={t.id}><select value={t.paper_type_id} onChange={e=>setTiers(v=>v.map(x=>x.id===t.id?{...x,paper_type_id:e.target.value}:x))}>{papers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={t.color_mode} onChange={e=>setTiers(v=>v.map(x=>x.id===t.id?{...x,color_mode:e.target.value}:x))}><option value="bw">P&B</option><option value="color">Colorido</option></select><input type="number" min="1" value={t.min_sheets} onChange={e=>setTiers(v=>v.map(x=>x.id===t.id?{...x,min_sheets:e.target.value}:x))}/><input type="number" min="1" value={t.max_sheets??''} placeholder="sem limite" onChange={e=>setTiers(v=>v.map(x=>x.id===t.id?{...x,max_sheets:e.target.value}:x))}/><input type="number" step="0.01" value={t.price_per_sheet} onChange={e=>setTiers(v=>v.map(x=>x.id===t.id?{...x,price_per_sheet:e.target.value}:x))}/><button onClick={()=>void save('print_price_tiers',t)}><Save size={14}/></button><button onClick={()=>void del('print_price_tiers',t.id)}><Trash2 size={14}/></button></div>)}</div></section>
<section className="card"><div className="title"><div><b>Serviços adicionais</b><small>Plastificação, encadernação, corte e outros.</small></div><button onClick={()=>setServices(v=>[...v,{id:crypto.randomUUID(),name:'Novo serviço',description:'',charge_type:'per_page',price:0,active:true,sort_order:v.length}])}><Plus size={14}/> Novo</button></div><div className="rows">{services.map(s=><div className="row service" key={s.id}><input value={s.name} onChange={e=>setServices(v=>v.map(x=>x.id===s.id?{...x,name:e.target.value}:x))}/><input value={s.description||''} onChange={e=>setServices(v=>v.map(x=>x.id===s.id?{...x,description:e.target.value}:x))}/><select value={s.charge_type} onChange={e=>setServices(v=>v.map(x=>x.id===s.id?{...x,charge_type:e.target.value}:x))}><option value="per_page">Por página</option><option value="per_sheet">Por folha</option><option value="per_document">Por documento</option><option value="flat">Fixo</option></select><input type="number" step="0.01" value={s.price} onChange={e=>setServices(v=>v.map(x=>x.id===s.id?{...x,price:e.target.value}:x))}/><label><input type="checkbox" checked={s.active} onChange={e=>setServices(v=>v.map(x=>x.id===s.id?{...x,active:e.target.checked}:x))}/> Ativo</label><button onClick={()=>void save('print_services',s)}><Save size={14}/></button><button onClick={()=>void del('print_services',s.id)}><Trash2 size={14}/></button></div>)}</div></section>
</section><style jsx global>{`.pa{min-height:100vh;background:#f5f5f2;color:#111;font-family:Inter,Arial,sans-serif}.shell{width:min(1180px,calc(100% - 30px));margin:auto;padding:28px 0 70px}.back{display:inline-flex;gap:7px;align-items:center;color:#666;text-decoration:none;font:800 11px Inter;margin-bottom:24px}.pa header p{margin:0 0 7px;color:#9b7600;font-size:10px;font-weight:900;letter-spacing:.2em}.pa h1{margin:0;font:italic 55px/1 'Barlow Condensed';text-transform:uppercase}.pa header span{display:block;margin-top:8px;color:#777;font-size:12px}.card{background:#fff;border:1px solid #dddcd7;border-radius:16px;padding:17px;margin-top:15px}.title{display:flex;justify-content:space-between;gap:10px;align-items:center;margin-bottom:12px}.title>div{display:grid;gap:4px}.title b{font-size:14px}.title small{font-size:10px;color:#888}.title button{border:0;background:#ffc400;border-radius:9px;padding:9px 11px;font:900 10px Inter;display:flex;align-items:center;gap:5px;cursor:pointer}.paper{display:grid;grid-template-columns:1.4fr .6fr auto 34px 34px;gap:7px;align-items:center;border-top:1px solid #eee;padding:9px 0}.row{display:grid;grid-template-columns:1.2fr .7fr .5fr .5fr .7fr 34px 34px;gap:6px;align-items:center}.row.service{grid-template-columns:1fr 1.2fr .8fr .6fr auto 34px 34px}.paper input,.row input,.row select{height:36px;border:1px solid #ddd;border-radius:8px;padding:0 8px;background:#fff;font:10px Inter;min-width:0}.paper label,.row label{font-size:9px;color:#777;display:flex;align-items:center;gap:4px}.paper button,.row button{height:34px;width:34px;border:1px solid #ddd;background:#fff;border-radius:8px;display:grid;place-items:center;cursor:pointer}.rows{display:grid;gap:6px}.loading{padding:80px;text-align:center;color:#888}@media(max-width:820px){.paper,.row,.row.service{grid-template-columns:1fr 1fr}.title{align-items:flex-start;flex-direction:column}.title button{width:100%;justify-content:center}}`}</style></main>;
}