'use client';

import { useEffect, useMemo, useState } from 'react';
import { Ban, Check, Smartphone, Monitor, Tablet, X, ShieldBan } from 'lucide-react';
import { usePathname } from 'next/navigation';

const SESSION_KEY = '2p-analytics-session';
type Device = { session_id: string; device_type: string; last_seen?: string; source?: string | null; ip_address?: string | null };
type ExcludedDevice = { session_id: string; label?: string | null; excluded_at: string };
type BlockedIp = { ip_address: string; label?: string | null; blocked_at: string };
const deviceLabel = (type: string) => type === 'mobile' ? 'Celular' : type === 'tablet' ? 'Tablet' : type === 'desktop' ? 'Computador' : 'Outro';
const DeviceIcon = ({ type }: { type: string }) => type === 'mobile' ? <Smartphone size={15} /> : type === 'tablet' ? <Tablet size={15} /> : <Monitor size={15} />;

export default function AnalyticsDeviceExclusion() {
  const pathname = usePathname();
  const [open, setOpen] = useState(false), [currentId, setCurrentId] = useState(''), [currentIp, setCurrentIp] = useState('');
  const [excluded, setExcluded] = useState<ExcludedDevice[]>([]), [blockedIps, setBlockedIps] = useState<BlockedIp[]>([]), [detected, setDetected] = useState<Device[]>([]), [label, setLabel] = useState(''), [busy, setBusy] = useState<string | null>(null);
  const load = async () => { try { const id = localStorage.getItem(SESSION_KEY) || ''; setCurrentId(id); const response = await fetch(`/api/admin/analytics/devices?session_id=${encodeURIComponent(id)}`, { cache: 'no-store' }); if (!response.ok) return; const data = await response.json(); setCurrentIp(data.current_ip || ''); setExcluded(data.excluded_devices || []); setBlockedIps(data.blocked_ips || []); setDetected(data.detected_devices || []); } catch {} };
  useEffect(() => { if (pathname === '/admin/analytics') void load(); }, [pathname]);
  const currentExcluded = useMemo(() => excluded.some((item) => item.session_id === currentId), [excluded, currentId]);
  const blocked = useMemo(() => new Set(blockedIps.map((item) => item.ip_address)), [blockedIps]);
  async function action(actionName: string, payload: Record<string, string>) { const key = payload.ip_address || payload.session_id || actionName; setBusy(key); try { const response = await fetch('/api/admin/analytics/devices', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: actionName, ...payload }) }); if (!response.ok) throw new Error(); await load(); } catch {} finally { setBusy(null); } }
  if (pathname !== '/admin/analytics') return null;
  const allDetected = detected.filter((device) => !excluded.some((item) => item.session_id === device.session_id));
  const actionStyle = { border:'1px solid #ddd', borderRadius:8, background:'#fff', padding:'7px 8px', fontSize:9, fontWeight:800, cursor:'pointer' as const };
  return <div style={{ position:'fixed', right:18, bottom:18, zIndex:80, width:'min(420px, calc(100vw - 24px))', background:'#fff', border:'1px solid #ddd', borderRadius:16, boxShadow:'0 12px 35px rgba(0,0,0,.16)', overflow:'hidden' }}>
    {!open ? <button onClick={()=>setOpen(true)} style={{width:'100%',border:0,background:'#111',color:'#fff',padding:'13px 15px',display:'flex',alignItems:'center',justifyContent:'space-between',cursor:'pointer',fontWeight:800,fontSize:12}}><span style={{display:'flex',alignItems:'center',gap:8}}><Ban size={15}/> Controle de dispositivos</span><span>{blockedIps.length} IP(s) · {excluded.length} dispositivo(s)</span></button> : <div>
      <div style={{padding:'13px 15px',background:'#111',color:'#fff',display:'flex',alignItems:'center',justifyContent:'space-between'}}><div><strong style={{fontSize:12}}>Controle de dispositivos</strong><div style={{fontSize:10,opacity:.7,marginTop:3}}>Exclua um dispositivo ou bloqueie toda a rede pelo IP.</div></div><button onClick={()=>setOpen(false)} aria-label="Fechar" style={{border:0,background:'transparent',color:'#fff',cursor:'pointer'}}><X size={17}/></button></div>
      <div style={{padding:14,maxHeight:'min(68vh,580px)',overflowY:'auto'}}>
        <div style={{border:'1px solid #e4e4e0',borderRadius:12,padding:11,marginBottom:12}}><div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center'}}><div><strong style={{fontSize:12}}>Este dispositivo</strong><div style={{color:'#777',fontSize:10,marginTop:3}}>{currentIp ? `IP da rede: ${currentIp}` : 'IP ainda não identificado'}</div></div><div style={{display:'flex',gap:6,flexWrap:'wrap',justifyContent:'flex-end'}}>{!currentExcluded ? <button disabled={busy===currentId} onClick={()=>void action('exclude',{session_id:currentId,label:label||'Meu dispositivo'})} style={actionStyle}>{busy===currentId?'...':'Excluir este dispositivo'}</button> : <button disabled={busy===currentId} onClick={()=>void action('include',{session_id:currentId})} style={actionStyle}>{busy===currentId?'...':'Restaurar dispositivo'}</button>}{currentIp && <button disabled={busy===currentIp||blocked.has(currentIp)} onClick={()=>void action('block_ip',{ip_address:currentIp,label:label||'Minha rede'})} style={{...actionStyle,background:blocked.has(currentIp)?'#eee':'#111',color:blocked.has(currentIp)?'#555':'#fff'}}>{busy===currentIp?'...':blocked.has(currentIp)?'IP bloqueado':'Bloquear IP'}</button>}</div></div>{!blocked.has(currentIp)&&<input value={label} onChange={e=>setLabel(e.target.value)} placeholder="Nome opcional: Casa" style={{width:'100%',marginTop:9,border:'1px solid #ddd',borderRadius:8,padding:8,fontSize:11}}/>}</div>
        {allDetected.length>0&&<div style={{marginBottom:13}}><strong style={{fontSize:11}}>Dispositivos detectados</strong>{allDetected.slice(0,12).map(device=><div key={device.session_id} style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:8,padding:'9px 0',borderBottom:'1px solid #eee'}}><div style={{minWidth:0}}><div style={{display:'flex',alignItems:'center',gap:6,fontSize:11,fontWeight:800}}><DeviceIcon type={device.device_type}/>{deviceLabel(device.device_type)}</div><div style={{color:'#777',fontSize:9,marginTop:2}}>{device.ip_address || 'IP não registrado'} · {device.last_seen ? new Date(device.last_seen).toLocaleString('pt-BR') : ''}</div></div><div style={{display:'flex',gap:5,flexWrap:'wrap',justifyContent:'flex-end'}}><button disabled={busy===device.session_id} onClick={()=>void action('exclude',{session_id:device.session_id,label:`${deviceLabel(device.device_type)} · excluído`})} style={actionStyle}>{busy===device.session_id?'...':'Excluir'}</button>{device.ip_address&&<button disabled={busy===device.ip_address||blocked.has(device.ip_address)} onClick={()=>void action('block_ip',{ip_address:device.ip_address,label:`Rede · ${deviceLabel(device.device_type)}`})} style={{...actionStyle,background:blocked.has(device.ip_address)?'#eee':'#111',color:blocked.has(device.ip_address)?'#555':'#fff'}}>{busy===device.ip_address?'...':blocked.has(device.ip_address)?'Bloqueado':'Bloquear IP'}</button>}</div></div>)}</div>}
        {blockedIps.length>0&&<div style={{marginBottom:13}}><strong style={{fontSize:11}}>IPs bloqueados</strong>{blockedIps.map(item=><div key={item.ip_address} style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:8,padding:'9px 0',borderBottom:'1px solid #eee'}}><div><div style={{display:'flex',alignItems:'center',gap:6,fontSize:11,fontWeight:800}}><ShieldBan size={14}/>{item.label||'Rede bloqueada'}</div><div style={{color:'#777',fontSize:9,marginTop:2}}>{item.ip_address} · {new Date(item.blocked_at).toLocaleString('pt-BR')}</div></div><button disabled={busy===item.ip_address} onClick={()=>void action('unblock_ip',{ip_address:item.ip_address})} style={{border:0,borderRadius:8,background:'#eee',padding:'7px 8px',fontSize:9,fontWeight:800,cursor:'pointer'}}>{busy===item.ip_address?'...':'Desbloquear'}</button></div>)}</div>}
        {excluded.length>0&&<div><strong style={{fontSize:11}}>Dispositivos excluídos</strong>{excluded.map(device=><div key={device.session_id} style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:8,padding:'9px 0',borderBottom:'1px solid #eee'}}><div><div style={{fontSize:11,fontWeight:800}}>{device.label||'Dispositivo'}</div><div style={{color:'#777',fontSize:9}}>{device.session_id.slice(0,8)} · {new Date(device.excluded_at).toLocaleString('pt-BR')}</div></div><button disabled={busy===device.session_id} onClick={()=>void action('include',{session_id:device.session_id})} style={{border:0,borderRadius:8,background:'#eee',padding:'7px 8px',fontSize:9,fontWeight:800,cursor:'pointer'}}>{busy===device.session_id?'...':'Restaurar'}</button></div>)}</div>}
      </div>
    </div>}
  </div>;
}
