export type LocalCreativeInput={type:'story'|'reel';product:{name:string;price:number|string;image_url?:string|null};objective:string;onProgress?:(message:string)=>void};
export type LocalCreative={title:string;strategy:string;image:string};

const CACHE_KEY='2pbox-local-engine-v1';

function escapeText(v:string){return v.replace(/[<>&'"]/g,(c)=>({'<':'&lt;','>':'&gt;','&':'&amp;',"'":'&apos;','"':'&quot;'} as Record<string,string>)[c]||c)}
function strategy(type:'story'|'reel',objective:string){const o=objective.toLowerCase();if(o.includes('clique'))return type==='story'?'Oferta + benefício + CTA direto':'Gancho visual + benefício + CTA';if(o.includes('venda'))return 'Produto + prova visual + urgência comercial';return type==='story'?'Curiosidade + benefício + CTA':'Gancho + demonstração + CTA'}
async function loadImage(url?:string|null){if(!url)return null;return await new Promise<HTMLImageElement|null>(resolve=>{const i=new Image();i.crossOrigin='anonymous';i.onload=()=>resolve(i);i.onerror=()=>resolve(null);i.src=url})}
function cacheReady(){try{localStorage.setItem(CACHE_KEY,JSON.stringify({ready:true,updatedAt:Date.now()}))}catch{}}
function draw(ctx:CanvasRenderingContext2D,w:number,h:number,p:any,img:HTMLImageElement|null,frame=0){ctx.fillStyle='#F5F5F2';ctx.fillRect(0,0,w,h);ctx.fillStyle='#FFC400';ctx.fillRect(0,0,w,190);ctx.fillStyle='#111';ctx.font='900 '+Math.round(w*.067)+'px Arial';ctx.fillText('2P BOX',Math.round(w*.067),112);ctx.fillStyle='#111';ctx.font='800 '+Math.round(w*.041)+'px Arial';ctx.fillText(frame?'VER PRODUTOS':'NOVIDADE',Math.round(w*.067),300);ctx.font='900 '+Math.round(w*.068)+'px Arial';const words=String(p.name).split(' ');let line='',y=420;for(const word of words){const t=line?line+' '+word:word;if(ctx.measureText(t).width>w*.84){ctx.fillText(line,w*.067,y);y+=88;line=word}else line=t}if(line)ctx.fillText(line,w*.067,y);if(img){const bx=w*.067,by=Math.min(y+80,h*.42),bw=w*.866,bh=h*.35,scale=Math.min(bw/img.width,bh/img.height)*(1+frame*.008),dw=img.width*scale,dh=img.height*scale;ctx.drawImage(img,bx+(bw-dw)/2,by+(bh-dh)/2,dw,dh)}ctx.fillStyle='#111';ctx.fillRect(0,h-360,w,360);ctx.fillStyle='#FFC400';ctx.font='900 '+Math.round(w*.054)+'px Arial';ctx.fillText('R$ '+Number(p.price).toFixed(2).replace('.',','),Math.round(w*.067),h-235);ctx.fillStyle='#fff';ctx.font='800 '+Math.round(w*.033)+'px Arial';ctx.fillText('COMPRE ONLINE  •  RECEBA HOJE',Math.round(w*.067),h-155);ctx.fillStyle='#FFC400';ctx.font='900 '+Math.round(w*.039)+'px Arial';ctx.fillText('VER PRODUTOS  →',Math.round(w*.067),h-82)}
export async function generateLocalCreative(input:LocalCreativeInput):Promise<LocalCreative>{const progress=input.onProgress||(()=>{});progress('Diretor-Geral: organizando campanha...');await new Promise(r=>setTimeout(r,60));progress('Copywriter + Estrategista: definindo mensagem...');await new Promise(r=>setTimeout(r,60));progress('Diretor de Arte + Designer: renderizando no navegador...');const c=document.createElement('canvas');c.width=1080;c.height=1920;const ctx=c.getContext('2d');if(!ctx)throw new Error('Canvas indisponível neste navegador.');const img=await loadImage(input.product.image_url);draw(ctx,1080,1920,input.product,img,0);cacheReady();progress('Revisor: conferindo identidade, preço e CTA...');return{title:escapeText(input.product.name),strategy:strategy(input.type,input.objective),image:c.toDataURL('image/jpeg',.94)}}