'use client';
import {FormEvent,useEffect,useState,Suspense} from 'react';
import Link from 'next/link';
import {ArrowLeft,CheckCircle2,Loader2,UserRound,Store,MessageCircle,FileText,LockKeyhole,ShieldCheck,MapPin} from 'lucide-react';
import {useSearchParams} from 'next/navigation';
import {useCart} from '@/components/cart-provider';
import {supabase} from '@/lib/supabase';

type Delivery='pickup'|'whatsapp_shipping';
type AuthUser={id:string;email?:string|null;user_metadata?:{full_name?:string;phone?:string;cpf?:string}};
type AuthData={user:AuthUser|null};
const WHATSAPP=process.env.NEXT_PUBLIC_WHATSAPP||'5511999999999';
function CheckoutForm(){
 const{items,total,clear}=useCart();const searchParams=useSearchParams();
 const[name,setName]=useState(''),[phone,setPhone]=useState(''),[email,setEmail]=useState(''),[cpf,setCpf]=useState(''),[password,setPassword]=useState(''),[type,setType]=useState<Delivery>('pickup'),[notes,setNotes]=useState('');
 const[cep,setCep]=useState(''),[street,setStreet]=useState(''),[number,setNumber]=useState(''),[complement,setComplement]=useState(''),[neighborhood,setNeighborhood]=useState(''),[city,setCity]=useState(''),[state,setState]=useState('');
 const[user,setUser]=useState<AuthUser|null>(null),[status,setStatus]=useState(''),[done,setDone]=useState(false),[orderId,setOrderId]=useState('');
 useEffect(()=>{setType(searchParams.get('entrega')==='shipping'?'whatsapp_shipping':'pickup');const client=supabase;if(!client)return;client.auth.getUser().then(({data}: {data:AuthData})=>{if(data.user){setUser(data.user);setEmail(data.user.email||'');setName(data.user.user_metadata?.full_name||'');setPhone(data.user.user_metadata?.phone||'');setCpf(data.user.user_metadata?.cpf||'')}})},[searchParams]);
 async function submit(e:FormEvent){e.preventDefault();const client=supabase;if(!client||!items.length)return;setStatus('');
  if(!name.trim()||!phone.trim()||!email.trim()){setStatus('Preencha nome, telefone e e-mail.');return}
  if(!user&&password.length<6){setStatus('Crie uma senha com pelo menos 6 caracteres.');return}
  if(type==='whatsapp_shipping'&&(!cep.trim()||!street.trim()||!number.trim()||!neighborhood.trim()||!city.trim()||!state.trim())){setStatus('Preencha o endereço para calcular o frete pelo WhatsApp.');return}
  setStatus(user?'Registrando seu pedido...':'Criando sua conta e registrando o pedido...');let currentUser=user;
  if(!currentUser){const{data,error}=await client.auth.signUp({email:email.trim(),password,options:{data:{full_name:name.trim(),phone:phone.trim(),cpf:cpf.replace(/\D/g,'')||null}}});if(error){setStatus(error.message.includes('already')?'Este e-mail já possui uma conta. Entre na sua conta e depois finalize a compra.':error.message);return}if(!data.user){setStatus('Não foi possível criar sua conta. Tente novamente.');return}if(!data.session){setStatus('Sua conta foi criada. Confirme o e-mail para concluir a compra.');return}currentUser=data.user as AuthUser;setUser(currentUser)}else{const{error}=await client.auth.updateUser({data:{full_name:name.trim(),phone:phone.trim(),cpf:cpf.replace(/\D/g,'')||null}});if(error){setStatus(error.message);return}}
  const address=type==='whatsapp_shipping'?{postal_code:cep.trim(),street:street.trim(),number:number.trim(),complement:complement.trim(),neighborhood:neighborhood.trim(),city:city.trim(),state:state.trim(),recipient_name:name.trim(),phone:phone.trim()}:null;
  const{data,error}=await client.rpc('create_order_with_stock_v2',{p_customer_name:name.trim(),p_customer_phone:phone.trim(),p_customer_email:email.trim(),p_delivery_type:type,p_notes:notes.trim()||null,p_items:items.map(i=>({id:i.id,quantity:i.quantity})),p_delivery_address:address});
  if(error){setStatus(error.message.replace(/^.*?: /,''));return}
  const id=data as string;setOrderId(id);const list=items.map(i=>`${i.quantity}x ${i.name} — R$ ${(i.price*i.quantity).toFixed(2).replace('.',',')}`).join('\n');
  const addressText=address?`\n\nENDEREÇO PARA FRETE\n${address.street}, ${address.number}${address.complement?` — ${address.complement}`:''}\n${address.neighborhood} — ${address.city}/${address.state}\nCEP: ${address.postal_code}`:'';
  clear();setDone(true);const msg=`Olá, 2P Box!\n\nQuero calcular o frete para o pedido ${id}.\n\nCliente: ${name}\nTelefone: ${phone}\nE-mail: ${email}\n\n${list}\n\nTotal dos produtos: R$ ${total.toFixed(2).replace('.',',')}\nForma de recebimento: ${type==='pickup'?'Retirada na loja':'Entrega — calcular frete pelo WhatsApp'}${addressText}${notes?`\n\nObservações: ${notes}`:''}`;
  if(type==='whatsapp_shipping')window.setTimeout(()=>{window.location.href=`https://wa.me/${WHATSAPP.replace(/\D/g,'')}?text=${encodeURIComponent(msg)}`},700);
 }
 if(done)return <main><div className="topbar">Pedido recebido • 2P Box</div><section className="container section checkout-success"><div className="category checkout-success-card"><div className="success-icon"><CheckCircle2 size={42}/></div><p className="eyebrow">TUDO CERTO</p><h1 className="checkout-title">Pedido recebido!</h1><p>Seu pedido <strong>{orderId}</strong> foi registrado. {type==='whatsapp_shipping'?'O WhatsApp será aberto para calcular o frete.':'Agora é só aguardar a confirmação da 2P Box para retirar na loja.'}</p><div style={{display:'flex',gap:10,justifyContent:'center',flexWrap:'wrap',marginTop:18}}><Link href="/conta" className="primary">Minha conta</Link><Link href="/loja" className="secondary">Voltar à loja</Link></div></div></section></main>;
 const deliveryLabel=type==='pickup'?'Retirada na loja':'Calcular frete pelo WhatsApp';
 return <main><div className="topbar">Finalizar pedido <span>•</span> 2P Box</div><header className="header container checkout-header"><Link href="/" className="brand"><img className="brand-logo" src="/logo.pnh.png" alt="2P Box"/><div className="store-brand-copy"><strong>FINALIZAR PEDIDO</strong><small>INFORMAÇÕES PARA O SEU PEDIDO</small></div></Link></header>
 <section className="container section checkout-page"><Link href="/carrinho" className="secondary"><ArrowLeft size={16}/> Voltar ao carrinho</Link><div className="checkout-intro"><p className="eyebrow">ÚLTIMA ETAPA</p><h1 className="checkout-title">Finalizar pedido</h1><p>{user?'Seus dados já estão preenchidos. Confira antes de confirmar.':'Compre sem cadastro prévio. No final, crie uma senha e sua conta será ativada para acompanhar seus pedidos.'}</p></div>
 <form onSubmit={submit} className="checkout-form category">
  <div className="checkout-section"><div className="checkout-section-heading"><UserRound size={20}/><div><h2>Seus dados</h2><p>{user?'Dados da sua conta':'Usados para identificar e confirmar seu pedido'}</p></div></div><div className="form-grid"><label>Nome completo<input required placeholder="Digite seu nome" value={name} onChange={e=>setName(e.target.value)}/></label><label>WhatsApp / telefone<input required placeholder="(11) 99999-9999" value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>E-mail<input required type="email" placeholder="seuemail@email.com" value={email} onChange={e=>setEmail(e.target.value)} disabled={!!user}/></label><label>CPF <span>(opcional)</span><input inputMode="numeric" placeholder="000.000.000-00" value={cpf} onChange={e=>setCpf(e.target.value)}/></label>{!user&&<label>Crie uma senha<input required type="password" minLength={6} placeholder="Mínimo de 6 caracteres" value={password} onChange={e=>setPassword(e.target.value)}/></label>}</div>{!user&&<div className="account-notice"><ShieldCheck size={18}/><span>Ao concluir, seu e-mail e senha criarão sua conta 2P Box automaticamente. Você poderá acompanhar pedidos, favoritos e seus dados nas próximas compras.</span></div>}</div>
  <div className="checkout-section delivery-confirmation"><div className="checkout-section-heading"><Store size={20}/><div><h2>Forma de recebimento</h2><p>Escolhida no carrinho</p></div></div><div className="delivery-confirmed"><div className="delivery-confirmed-icon">{type==='pickup'?<Store size={22}/>:<MessageCircle size={22}/>}</div><div><strong>{deliveryLabel}</strong><span>{type==='pickup'?'Sem endereço e sem frete. Você conclui o pedido normalmente.':'O endereço só é solicitado para calcular o frete e será enviado junto com o pedido pelo WhatsApp.'}</span></div><LockKeyhole size={16}/></div><Link href="/carrinho" className="change-delivery">Voltar ao carrinho para alterar a forma de recebimento</Link></div>
  {type==='whatsapp_shipping'&&<div className="checkout-section"><div className="checkout-section-heading"><MapPin size={20}/><div><h2>Endereço para o frete</h2><p>Preencha para enviarmos ao WhatsApp e calcularmos o valor da entrega.</p></div></div><div className="form-grid address-grid"><label>CEP<input required inputMode="numeric" placeholder="00000-000" value={cep} onChange={e=>setCep(e.target.value)}/></label><label>Rua / avenida<input required placeholder="Nome da rua" value={street} onChange={e=>setStreet(e.target.value)}/></label><label>Número<input required placeholder="123" value={number} onChange={e=>setNumber(e.target.value)}/></label><label>Complemento <span>(opcional)</span><input placeholder="Apto, bloco..." value={complement} onChange={e=>setComplement(e.target.value)}/></label><label>Bairro<input required placeholder="Seu bairro" value={neighborhood} onChange={e=>setNeighborhood(e.target.value)}/></label><label>Cidade<input required placeholder="Sua cidade" value={city} onChange={e=>setCity(e.target.value)}/></label><label>Estado<input required maxLength={2} placeholder="SP" value={state} onChange={e=>setState(e.target.value.toUpperCase())}/></label></div><div className="shipping-whatsapp-note"><MessageCircle size={17}/><span>Ao clicar no botão abaixo, enviaremos <strong>o pedido completo + endereço</strong> para a 2P Box no WhatsApp, já identificado como pedido de cálculo de frete.</span></div></div>}
  <div className="checkout-section"><div className="checkout-section-heading"><FileText size={20}/><div><h2>Observações</h2><p>Alguma informação adicional?</p></div></div><textarea placeholder="Escreva uma observação, se necessário..." value={notes} onChange={e=>setNotes(e.target.value)}/></div>
  {status&&<div className="checkout-status"><Loader2 size={17}/>{status}</div>}
  <div className="checkout-footer"><div><span>Total dos produtos</span><strong>R$ {total.toFixed(2).replace('.',',')}</strong></div><button className={`primary checkout-submit ${type==='whatsapp_shipping'?'whatsapp-submit':''}`} disabled={!items.length||!!done}>{items.length?(type==='whatsapp_shipping'?'Calcular frete pelo WhatsApp':user?'Confirmar pedido':'Criar conta e finalizar pedido'):'Carrinho vazio'}</button></div>
 </form></section>
 <style jsx global>{`.delivery-confirmed{display:flex;align-items:center;gap:14px;padding:17px;border:1px solid #d9d9d9;border-radius:12px;background:#fafafa;color:#111}.delivery-confirmed-icon{width:42px;height:42px;flex:none;border-radius:9px;background:#ffc400;display:grid;place-items:center}.delivery-confirmed>div:nth-child(2){display:grid;gap:5px;flex:1}.delivery-confirmed strong{font-size:14px}.delivery-confirmed span{font-size:11px;color:#666;line-height:1.4}.delivery-confirmed>svg{color:#888;flex:none}.change-delivery{display:inline-block;margin-top:11px;font-size:11px;color:#777;text-decoration:underline}.account-notice{display:flex;align-items:flex-start;gap:10px;padding:13px 14px;margin-top:16px;background:#fff9d9;border:1px solid #f0d65b;border-radius:9px;color:#5c5000;font-size:11px;line-height:1.5}.account-notice svg{flex:none;color:#a47700;margin-top:1px}.address-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.shipping-whatsapp-note{display:flex;align-items:flex-start;gap:9px;margin-top:15px;padding:13px 14px;border-radius:9px;background:#f4f4f4;color:#555;font-size:11px;line-height:1.5}.shipping-whatsapp-note svg{flex:none;color:#111}.whatsapp-submit{background:#ffc400!important;color:#111!important}@media(max-width:600px){.address-grid{grid-template-columns:1fr}}`}</style></main>
}
export default function Checkout(){return <Suspense fallback={<main><div className="topbar">Finalizar pedido • 2P Box</div><section className="container section"><p>Carregando checkout...</p></section></main>}><CheckoutForm/></Suspense>}
